imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: repository.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    locale: en
    available_locales: ["%locale%", "de"]
    uploads_path: /uploads
    images_path: /images
    dropdown_status:
        Active: 1
        Inactive: 0
    dropdown_roles: { 'Data Entry Operator': 'ROLE_DEO', 'Administrator': 'ROLE_ADMIN', 'Staff': 'ROLE_STAFF' }

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    templating:
        engines: ['twig', 'php']
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        save_path: null
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        uploads_path: "%uploads_path%"
        images_path: "%images_path%"
        logo_url: "%logo_url%"
        favicon_url: "%favicon_url%"
        organization_url: "%organization_url%"
        organization_name: "%organization_name%"
        project_name: "%project_name%"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset:  "%database_charset%"
        options:
            1002: "SET NAMES '%database_charset%' COLLATE '%database_collation%'"
        mapping_types:
            enum: string
        logging:  true

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUser Bundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%sender_email%"
        sender_name: "%sender_name%"

# File Upload Configuration
vich_uploader:
    db_driver: orm
    mappings:
        uploads:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.root_dir%/../web%uploads_path%'
        images:
            uri_prefix: '%images_path%'
            upload_destination: '%kernel.root_dir%/../web%images_path%'

# TimeStamps related Configuration
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

# EasyAdminBundle Configuration
easy_admin:
    site_name: '<img src="%logo_url%" title=" %project_name% by %organization_name%" />'
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i:s'
        number:   '%.0u'
    list:
        max_results: 20
    design:
        brand_color: '#F9B000'
        color_scheme: 'light'
        assets:
            favicon: '%favicon_url%'
        menu:
            - { entity: 'User', label: 'Manage Users', icon: 'users', role: ROLE_APP_ADMIN }
            - label: 'Manage Trainings'
              icon: 'archive'
              role: ROLE_APP_ADMIN
              children:
                - { entity: 'Track', label: 'Manage Learning Tracks', icon: 'folder', role: ROLE_APP_ADMIN }
                - { entity: 'Course', label: 'Manage Courses', icon: 'file', role: ROLE_APP_ADMIN }
                - { entity: 'Tag', label: 'Manage Tags', icon: 'tags', role: ROLE_APP_ADMIN }
#            - label: 'Configurations'
#              icon: 'cogs'
#              role: ROLE_ADMIN
#              children:
#                - { label: 'Preferences', route: 'shop_settings', icon: 'cogs', role: ROLE_ADMIN }

    entities:
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\Dashboard\UserController
            role: ROLE_APP_ADMIN
            label: 'Users'
            list:
                title: '%%entity_label%% Listing'
                help: 'A list of all the users at <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'fullName', label: 'Full Name' }
                    - { property: 'username', label: 'Username' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'enabled', label: 'Active', type: 'toggle' }
                    - { property: 'lastLogin', label: 'Last Login' }
                    - { property: 'roles', label: 'Role(s)' }
#                    - { property: 'courses', label: 'Course(s)' }
                actions:
                    - 'show'
                    - 'new'
                    - 'edit'
                    - 'delete'
            show:
                title: "User Details"
                help: 'Details of a specific user'
                fields:
                    - { property: 'fullName', label: 'Full Name' }
                    - { property: 'username', label: 'Username' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'enabled', label: 'Active', type: 'toggle' }
                    - { property: 'lastLogin', label: 'Last Login' }
                    - { property: 'roles', label: 'Role(s)' }
#                    - { property: 'courses', label: 'Course(s)' }
                actions:
                    - 'edit'
                    - 'delete'
                    - 'list'
            new:
                title: "Add New User"
                help: 'Add new user to <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'fullName', label: 'Full Name' }
                    - { property: 'username', label: 'Username' }
                    - { property: 'email', label: 'Email', type: 'email', type_options: { required: true } }
                    - { property: 'enabled', label: 'Active', type: 'choice', type_options: { choices: '%dropdown_status%' } }
                    - { property: 'plainPassword', type: 'text', type_options: { required: true } }
                    - { property: 'roles', label: 'Role(s)', type: 'choice', type_options: { multiple: true, choices: '%dropdown_roles%' } }
                form_options: { validation_groups: ['Registration'] }
            edit:
                title: "Edit User"
                help: 'Edit user from <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'fullName', label: 'Full Name' }
                    - { property: 'username', label: 'Username' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'enabled', label: 'Active', type: 'choice', type_options: { choices: '%dropdown_status%' } }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false} }
                    - { property: 'roles', label: 'Role(s)', type: 'choice', type_options: { multiple: true, choices: '%dropdown_roles%' } }
                form_options: { validation_groups: ['Profile'] }
        Course:
            class: AppBundle\Entity\Course
            controller: AppBundle\Controller\Dashboard\CourseController
            role: ROLE_APP_ADMIN
            label: 'Courses'
            list:
                title: '%%entity_label%% Listing'
                help: 'A list of all the uploaded courses to <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'thumb', label: 'Thumbnail', type: 'image', base_path: '%images_path%' }
                    - { property: 'link', label: 'Link' }
                    - { property: 'outDated', label: 'Is Upto Date?', type: 'boolean' }
                    - { property: 'tags', label: 'Tag(s)' }
                    - { property: 'status', label: 'Active', type: 'toggle' }
                actions:
                    - 'show'
                    - 'new'
                    - 'edit'
                    - 'delete'
            show:
                title: "Course Details"
                help: 'Details of a specific course'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'raw' }
                    - { property: 'thumb', label: 'Thumbnail', type: 'image', base_path: '%images_path%' }
                    - { property: 'link', label: 'Link' }
                    - { property: 'download', label: 'Tutorial File', type: 'file', base_path: '%uploads_path%' }
                    - { property: 'outDated', label: 'Is Upto Date?' }
                    - { property: 'tags', label: 'Tag(s)' }
                    - { property: 'status', label: 'Active', type: 'boolean' }
                actions:
                    - 'edit'
                    - 'delete'
                    - 'list'
            new:
                title: "Add New Course"
                help: 'Add new course to <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'ckeditor' }
                    - { property: 'thumbFile', label: 'Thumbnail', type: 'vich_image' }
                    - { property: 'link', label: 'Link', type: 'url' }
                    - { property: 'downloadFile', label: 'Tutorial File', type: 'file', help: 'Kindly upload zip file if course contains more than one files' }
                    - { property: 'outDated', label: 'Is Upto Date?' }
                    - { property: 'tracks', label: 'Learning Track(s)' }
                    - { property: 'tags', label: 'Tag(s)' }
                    - { property: 'status', label: 'Active', type: 'choice', type_options: { choices: '%dropdown_status%' } }
            edit:
                title: "Edit Course"
                help: 'Edit course from <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'ckeditor' }
                    - { property: 'thumbFile', label: 'Thumbnail', type: 'vich_image' }
                    - { property: 'link', label: 'Link', type: 'url' }
                    - { property: 'downloadFile', label: 'Tutorial File', type: 'file', help: 'Kindly upload zip file if course contains more than one files' }
                    - { property: 'outDated', label: 'Is Upto Date?' }
                    - { property: 'tracks', label: 'Learning Track(s)' }
                    - { property: 'tags', label: 'Tag(s)' }
                    - { property: 'status', label: 'Active', type: 'choice', type_options: { choices: '%dropdown_status%' } }
        Track:
            class: AppBundle\Entity\Track
            controller: AppBundle\Controller\Dashboard\TrackController
            role: ROLE_APP_ADMIN
            label: 'Learning Tracks'
            list:
                title: '%%entity_label%% Listing'
                help: 'A list of all the uploaded learning tracks available at <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'thumb', label: 'Thumbnail', type: 'image', base_path: '%images_path%' }
                    - { property: 'link', label: 'Link' }
                    - { property: 'courses', label: 'Course(s)' }
                    - { property: 'status', label: 'Active', type: 'toggle' }
                actions:
                    - 'show'
                    - 'new'
                    - 'edit'
                    - 'delete'
            show:
                title: "Learning Track Details"
                help: 'Details of a specific Learning Track'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'raw' }
                    - { property: 'thumb', label: 'Thumbnail', type: 'image', base_path: '%images_path%' }
                    - { property: 'link', label: 'Link' }
                    - { property: 'courses', label: 'Course(s)' }
                    - { property: 'status', label: 'Active', type: 'boolean' }
                actions:
                    - 'edit'
                    - 'delete'
                    - 'list'
            new:
                title: "Add New Learning Track"
                help: 'Add new Learning Track to <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'ckeditor' }
                    - { property: 'thumbFile', label: 'Thumbnail', type: 'vich_image' }
                    - { property: 'link', label: 'Link', type: 'url' }
                    - { property: 'courses', label: 'Course(s)' }
                    - { property: 'status', label: 'Active', type: 'choice', type_options: { choices: '%dropdown_status%' } }
            edit:
                title: "Edit Learning Track"
                help: 'Edit Learning Track from <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'ckeditor' }
                    - { property: 'thumbFile', label: 'Thumbnail', type: 'vich_image' }
                    - { property: 'link', label: 'Link', type: 'url' }
                    - { property: 'courses', label: 'Course(s)' }
                    - { property: 'status', label: 'Active', type: 'choice', type_options: { choices: '%dropdown_status%' } }
        Tag:
            class: AppBundle\Entity\Tag
            controller: AppBundle\Controller\Dashboard\TagController
            role: ROLE_APP_ADMIN
            label: 'Course Tags'
            list:
                title: '%%entity_label%% Listing'
                help: 'A list of all the courses related tags available at <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                actions:
                    - 'new'
                    - 'edit'
                    - 'delete'
            show:
                title: "Course Tag Details"
                help: 'Details of a specific Course Tag'
                fields:
                    - { property: 'title', label: 'Title' }
                actions:
                    - 'list'
                    - 'edit'
                    - 'delete'
            new:
                title: "Add New Course Tag"
                help: 'Add new Course Tag to <strong>%project_name%</strong> by <em>%organization_name%</em>'
                fields:
                    - { property: 'title', label: 'Title' }
                    - { property: 'description', label: 'Description', type: 'ckeditor' }
                    - { property: 'link', label: 'Link', type: 'url' }
                    - { property: 'courses', label: 'Course(s)' }

ivory_ck_editor:
      input_sync: true
      default_config: default
      configs:
          default:
              toolbar: [['Bold', 'Italic', 'Underline', 'Subscript', 'Superscript', '-', 'NumberedList', 'BulletedList'], ['Link', 'Unlink'], ['Find', '-', 'Cut', 'Copy', 'Paste', 'PasteFromWord', '-', 'Undo', 'Redo'], ['Source'], ['Preview']]