services:
  AppBundle\Repository\TrainingRepository:
      class: 'AppBundle\Repository\TrainingRepository'
      public: true
      factory: ["@doctrine", 'getRepository']
      arguments:
          - 'AppBundle:Training'