# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        exclude: '../../src/AppBundle/{Entity,Repository,Tests,Security,DataFixtures}'

    # Controllers
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # Seeders to populate essential data for application
    AppBundle\DataFixture\:
        resource: '../../src/AppBundle/DataFixture'
        tags: ['doctrine.fixture.orm']

    # Voters for security related decisions
    AppBundle\Security\Voter\:
        resource: '../../src/AppBundle/Security/Voter'
        arguments:
          - '@security.access.decision_manager'
        tags: ['security.voter']

    # Logic after successful login (Redirection etc)
    AppBundle\Security\AuthenticationHandler:
        class: AppBundle\Security\AuthenticationHandler
        arguments:
          - '@security.authorization_checker'
          - '@router'

    # Required for session storage in DB
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        public: false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_table: session, db_username: '%database_user%', db_password: '%database_password%' }